### PR TITLE
fix(#126): Improves build time

### LINKED ISSUE #126: Build time improvement
As we are adding more and more functional tests our build is taking quite a bit of time which will make it harder to have fast feedback loops (either locally or on the CI server). It bumped from ~4:30min to above 7 on my local machine:

```
[INFO] Reactor Summary:                                                                                                                       
[INFO]                                                                                                                                        
[INFO] Smart testing ...................................... SUCCESS [  0.727 s]                                                               
[INFO] smart-testing-core ................................. SUCCESS [ 13.491 s]                                                               
[INFO] junit-test-result-parser ........................... SUCCESS [  1.728 s]                                                               
[INFO] smart-testing-surefire-provider .................... SUCCESS [  7.337 s]                                                               
[INFO] smart-testing-strategy-changed ..................... SUCCESS [  4.464 s]                                                               
[INFO] smart-testing-strategy-affected .................... SUCCESS [  9.435 s]                                                               
[INFO] smart-testing-strategy-failed ...................... SUCCESS [  2.511 s]                                                               
[INFO] smart-testing-maven-lifecycle-extension ............ SUCCESS [  4.022 s]                                                               
[INFO] smart-testing-test-bed ............................. SUCCESS [07:17 min]                                                               
[INFO] ------------------------------------------------------------------------                                                               
[INFO] BUILD SUCCESS               
[INFO] ------------------------------------------------------------------------                                                               
[INFO] Total time: 07:49 min (Wall Clock)                              
[INFO] Finished at: 2017-09-05T22:17:52+02:00                          
[INFO] Final Memory: 40M/1385M     
[INFO] ------------------------------------------------------------------------ 
```

We should review our Test Bed tests in order to:

  * minimize redundant/overlapping tests
  * identify those which we could test in isolation (unit tests)
  * narrow the builds for only relevant modules, e.g. `.build("config/impl-base")` where necessary

### PR DESCRIPTION
**Pull request by lordofthejars**
#### Short description of what this resolves:

Improves build time by ignoring overlapping tests and narrow builds

#### Changes proposed in this pull request:

- Ignores tests that are overlapped with other tests. Currently they are just ignored.
- Narrow build to modules that received change.

Fixes #126

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Can you link to the redundant test? Hard to find on the mobile ;) I also don't feel confident about having ignored test as a solution. Maybe we could evaluate the overlap and decide what to change as part of this PR?

**Comment by lordofthejars** [comment]
Ignored tests it is a partial solution before we agreed that they are
really redundant. Just that I have not missed something.

**Comment by lordofthejars** [comment]
* https://github.com/arquillian/smart-testing/blob/master/functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest.java should be removed. In this case we are testing that a test is detected between two commits but then there is another test https://github.com/arquillian/smart-testing/blob/master/functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/affected/ChangesOnDifferentModulesAffectedTestsSelectionExecutionFunctionalTest.java that checks exactly the same but when changes occurs also in other modules, so effectively the functional test of checking the tests between a range of commits are tested in both and the latter one fully overlaps with the first one, so for this reason there is no rewrite but a remove of the test. (Now ignored and when we agree removed)

* https://github.com/arquillian/smart-testing/blob/master/functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/failed/HistoricalChangesFailedTestsSelectionExecutionFunctionalTest.java test should be ignored because failed strategy does not use any local or scm changes, just gets previous failures, so this test can be removed.

**Comment by MatousJobanek** [comment]
I'm not sure if ignoring the tests is the best solution. Maybe putting these semi-redundant test classes into another test suite that will be executed nightly. But yeah, if we agree on that they are redundant, we can remove them.
As for the [HistoricalChangesFailedTestsSelectionExecutionFunctionalTest.java](https://github.com/arquillian/smart-testing/blob/master/functional-tests/test-bed/src/test/java/org/arquillian/smart/testing/ftest/failed/HistoricalChangesFailedTestsSelectionExecutionFunctionalTest.java) test - is that really a redundant test, or just a bug?

I believe that we haven't used all possibilities of parallelism. I've been playing with it some time ago - I'll share a link with my work/attempt.

**Comment by lordofthejars** [comment]
>  HistoricalChangesFailedTestsSelectionExecutionFunctionalTest.java

It is a bug or a none sense test. Failed strategy does not check historical scm data, so this test can be removed because it is testing exactly the same as the other one.

**Comment by lordofthejars** [comment]
> ignoring the tests is the best solution

As I said is a temporal solution until we decide to remove them

**Comment by MatousJobanek** [comment]
Check this commit: https://github.com/MatousJobanek/smart-testing/commit/02d91978ee21fbb2261d03de7594449dd89f03de

I'm combining several things there (the numbers of threads are just example):
* the test-bed build uses Maven parallelism with 50 threads per cpu core - for more information take a look [here](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3)
* the same is used for build invocation on Travis (could be used locally)
* the Travis is building in three virtual machines at once - check [this](https://docs.travis-ci.com/user/speeding-up-the-build/): 
  * one for unit tests
  * one for functional tests - to separate unit tests and functional tests I had to introduce two profiles inside of the pom files
  * one for generating documentation - no to do it in the previous builds/vm twice

* speeding up Java startup using properties: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

The local build `mvn clean install -T 100` now takes 04:28
The build on travis:
```
Ran for 14 min 41 sec
Total time 18 min 41 sec 
```
see here: https://travis-ci.org/MatousJobanek/smart-testing/builds/282751554

**Comment by MatousJobanek** [comment]
I'll send it as a PR if you're fine with it...

**Comment by lordofthejars** [comment]
Of course I am fine, it is our PR initially implemented by me :)

**Comment by MatousJobanek** [comment]
Here it is - as a separated PR: https://github.com/arquillian/smart-testing/pull/204
This one is still yours :-)
I went through the tests you ignored and I'm fine with removing the failed one: `HistoricalChangesFailedTestsSelectionExecutionFunctionalTest.java`
But I would keep the `HistoricalChangesAffectedTestsSelectionExecutionFunctionalTest.java` as it tests on different granularity than the other one.

**Comment by lordofthejars** [comment]
Ok, it is fine for me

**Comment by lordofthejars** [comment]
@MatousJobanek updated. If you agree we can merge.

**Comment by bartoszmajsak** [comment]
I just wanted to catch up on it - I don't see an approval from Matous and yet you asked him 

> If you agree we can merge.

Did you guys took it offline or it was just merged?

**Comment by lordofthejars** [comment]
@bartoszmajsak we talked on mattermost.

**Comment by bartoszmajsak** [comment]
How much did we improve the build time after this PR got merged @lordofthejars ?

**Pull request merged**
