### PR TITLE
Remove redundant code & fix string concatenation

### PR DESCRIPTION
**Pull request by dipak-pawar**
#### Changes proposed in this pull request:

- Removes redundant code for ST configuration in pom.xml for initial approach.
- Corrected string concatenation to log correct message.

### CODE REVIEW

**Comment by MatousJobanek** [comment]
@dipak-pawar could you please rebase it with latest changes from the master branch?

**Comment by lordofthejars** [comment]
@MatousJobanek it seems it is still mergable

**Comment by dipak-pawar** [comment]
@lordofthejars I rebased it. So it's mergeable

**Comment by lordofthejars** [comment]
@dipak-pawar Ok now I only see the original commit. But anyway, when Matous gives the ok, let's merge

**Comment by MatousJobanek** [comment]
Thank you @dipak-pawar

**Comment by bartoszmajsak** [comment]
I have a feeling this concatenation was already fixed before. Was it lost in some other merge or is it a different place where we had a similar mistake?

**Comment by dipak-pawar** [comment]
> I have a feeling this concatenation was already fixed before. Was it lost in some other merge or is it a different place where we had a similar mistake?

@bartoszmajsak yes I submitted #130 with this fix. But we decided to not go with that change which contains more than concatenation fix. So I closed that PR. Hence we have this change here.

**Pull request merged**
